version: '3.8'

services:
  frontend:
    image: product/frontend
    restart: always
    build: ./react-ui
    ports:
      - "3000:3000"
    networks:
      - web_network
  
  backend:
    container_name: appseed_app
    image: product/backend
    restart: always
    build: ./django-api
    networks:
      - db_network
      - web_network
  
  nginx:
    image: "nginx:latest"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./django-api/nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - backend

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
